Adds Project Base Model, View and Placeholder HTML
NCEAS/metacatui pull request #2032
Opened 2022-06-29 19:19 UTC by helbashandy

Closes #1945

* Adds a base Project model and collection that can be populated
 either from a default or a direct API. In the case of populating
 from the API, extending member nodes will have to extend the Parse
 function if any data structure handling is needed.

* Adds tests for project model and collection.

* Adds a Project view with some functinality to handle basic view
project selection and rendering.

* Adds a projects info template as a placeholder for extending nodes.

Co-authors: Mario Melara, Val Hendrix

2022-06-29 19:32 UTC, helbashandy commented
Hi @laurenwalker - From our discussion with @mbjones, we figured that the best timeline that works with our deliverables is that we merge this PR in a minor release within the 2.x.x major before July 30th. The same timeline applies to https://github.com/NCEAS/metacatui/issues/2024 which @mamelara will submit a PR for soon. 

Thanks for taking the time to take a look at the PR and please let me know about any feedback for future contributions.

2022-06-30 16:07 UTC, laurenwalker commented
Thanks @helbashandy and @mamelara, I will review these as soon as I can!

2022-07-12 18:37 UTC, laurenwalker requested changes
Thanks @helbashandy, this looks great. My only requested change is to add class level documentation for the new Project, ProjectList, and ProjectView classes via JSDoc (see https://github.com/NCEAS/metacatui/blob/main/CONTRIBUTING.md#documentation). 

I've also gradually been trying to use UnderscoreJS less and less in MetacatUI in favor of vanilla JS so we can remove it completely someday. That's not a necessary change for your PR, but would be helpful! (e.g. replacing _.each with a for loop or Array.forEach())

2022-07-13 16:41 UTC, helbashandy commented
Thanks for reviewing @laurenwalker - I made the suggested documentation changes and removed UnderscoreJS from the model and collection. 

I left it as is on the view as it seems like I have to install other dependencies to load up the template html into the view `template` attribute. Is there a reference you can point me to that compiles the template into a render-able function that uses Vanilla JS that can be used in the view?

2022-07-14 18:56 UTC, laurenwalker commented
@helbashandy I've been using JS [template literals ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) in place of Underscore's template engine. This does mean that the JS expressions inside the template need to be kept simple (e.g. no big for loops) but I think that is good practice so that our templates aren't performing lots of logic.

2022-07-20 22:10 UTC, helbashandy commented
Hi @laurenwalker - I explored removing the whole underscoreJS template syntax completely from the example code of the `projectInfo.html` file, but realized that I would need to have a template literal engine to process the template literal syntax, as the html file is imported as a text string and would need to be evaluated for the template literal to be processed instead of rendering as text. As it seems like MetacatUI didn't adapt any template literal engines yet (literals were used directly in the JS views and not imported from an HTML file), I only replaced the underscoreJS template functions with the Vanilla HTML.

2022-07-21 14:53 UTC, laurenwalker commented
Thanks for making those changes Hesham. Using the Underscore templates for now is ok until we come up with a more formal solution.

However the tests are not running on your branch. When I look at the GitHub Actions results, it says the action passed/completed ok but when you look at the run details, it says there are `FAILS: 0 PASSES:0`. When I checked out your branch and ran the tests via `npm view-tests`, there are Javascript errors in the console:

```
The resource from “http://localhost:3001/src/js/js/specs/unit/models/project/Project.spec.js?v=undefined” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[test](http://localhost:3001/test/)
Loading failed for the <script> with source “http://localhost:3001/src/js/js/specs/unit/models/project/Project.spec.js?v=undefined”. [test:1:1](http://localhost:3001/test/)
Uncaught Error: Script error for: js/specs/unit/models/project/Project.spec
http://requirejs.org/docs/errors.html#scripterror
    makeError http://localhost:3001/src/components/require.js:163
    onScriptError http://localhost:3001/src/components/require.js:1666
[require.js:163:17](http://localhost:3001/src/components/require.js)
The resource from “http://localhost:3001/src/js/js/specs/unit/collections/ProjectList.spec.js?v=undefined” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[test](http://localhost:3001/test/)
Loading failed for the <script> with source “http://localhost:3001/src/js/js/specs/unit/collections/ProjectList.spec.js?v=undefined”. [test:1:1](http://localhost:3001/test/)
Uncaught Error: Script error for: js/specs/unit/collections/ProjectList.spec
http://requirejs.org/docs/errors.html#scripterror
    makeError http://localhost:3001/src/components/require.js:163
    onScriptError http://localhost:3001/src/components/require.js:1666
[require.js:163:17](http://localhost:3001/src/components/require.js)

​```

I will change the GitHub Action so that it wil fail when the tests fail to run at all.

2022-07-21 16:15 UTC, helbashandy commented
Hi @laurenwalker - This is strange, I have the tests running with no issues locally when I open up `index.html` of the tests dir.

<img width="1902" alt="Screen Shot 2022-07-21 at 9 12 24 AM" src="https://user-images.githubusercontent.com/47407500/180263123-eee6dc50-2e44-4100-871d-b0d11eb09c0d.png">

2022-07-21 18:30 UTC, merged