Adds enablePublishWithExistingDOI configuration
NCEAS/metacatui pull request #2203
Opened 2023-10-17 18:07 UTC by helbashandy

## Description

Adds `enablePublishWithExistingDOI` configuration. If true, users can see a "Publish" button in the MetadataView if enablePublishDOI is also enabled, even if a DOI is assigned to the dataset.

If false, the publish button will not show up when a DOI is already assigned to the dataset.

closes #2202

2023-10-18 12:09 UTC, robyngit requested changes
@helbashandy this looks great, thanks! Could you please just update the comments above your code changes to describe the new decision process?

2023-10-18 12:09 UTC, robyngit commented on src/js/models/AppModel.js
> +      * @default false
When this gets released, I update all the @since x.x.x with the new version.
```suggestion
      * @default false
      * @since x.x.x
```

2023-10-18 12:12 UTC, robyngit commented
@rushirajnenuji I imagine that your work on hierarchical folders could involve lots of changes to the MetadataView. Does this PR conflict with any of your work?

2023-10-18 18:20 UTC, rushirajnenuji commented
Thank you @robyngit  and @helbashandy  -- I'll review the code to see any conflicts with MDV and get back.

2023-10-23 16:36 UTC, rushirajnenuji approved these changes
Hi @robyngit  and @helbashandy  -- I reviewed this PR and it looks good. There are some minor conflicts with the MetaDataView, but it should be easy to merge into my branch. Thank you for checking.

2023-10-23 19:28 UTC, robyngit commented on src/js/models/AppModel.js
> +      * @default false
That's perfect @helbashandy, thank you! In the future, just use `x.x.x` as the version - these are all replaced with the actual version number at the time of release - that way there's flexibility if something has to get pushed to a different release, or the version # changes for any reason.

2023-10-23 20:11 UTC, robyngit commented
@helbashandy not sure what the expected behaviour is for ESS-DIVE, but it seems intuitive that if enablePublishDOI is false, the publish button should never show up. Likewise if publishing is limited to those in the enablePublishDOIForSubjects list, and the user isn’t authorized, then the publish button should never show up. So if we were to move this decision into its own method, the logic would be something like...

```js
canBePublished: function () {

  // The Publish feature has to be enabled in the app. 
  if (!MetacatUI.appModel.get("enablePublishDOI")) {
    return false;
  }

  // If the repository is configured to limit publishing to only certain
  // users and groups, then check if the logged-in user is one of the
  // subjects in the list or is in a group that is in the list. If not,
  // then this metadata cannot be published.
  const authorizedPublishers = MetacatUI.appModel.get("enablePublishDOIForSubjects");
  const authorizedOnly = Array.isArray(authorizedPublishers) &&
    (authorizedPublishers.length);
  const userIsAuthorized = authorizedOnly &&
    MetacatUI.appUserModel.hasIdentityOverlap(authorizedPublishers);
  if (authorizedOnly && !userIsAuthorized) {
    return false;
  }

  // Finally, if the setting to enable publishing on all private
  // metadata is enabled, then allow publishing if the metadata is not
  // yet public. Otherwise, allow publishing if there's not a DOI yet.
  const isPrivate = !this.get("isPublic")
  const isDOI = model.isDOI()
  const enablePublishOnAllPrivate = MetacatUI.appModel.get("enablePublishOnAllPrivate");
  if ((enablePublishOnAllPrivate && isPrivate) || !isDOI) {
    return true;
  }

  // Otherwise, this metadata cannot be published.
  return false;

},
```

What do you think?

2024-04-01 16:46 UTC, robyngit commented
Hey @helbashandy, wondering if ESS-Dive is still hoping to merge in these changes and add a enablePublishOnAllNonPublic config option?

2024-06-04 20:43 UTC, robyngit commented
I will close this PR for now since it hasn't had attention for 7+ months, but @helbashandy please re-open if you're still wanting to get this merged into MetacatUI!

2024-06-04 20:43 UTC, closed without merging

2024-06-04 21:22 UTC, helbashandy commented
Hi Robyn,

I apologize for the delayed response. Regarding the pending PR, we were in the process of finalizing design changes that impact the ESS-DIVE user journey for publication requests. After consideration of our current use-cases, we determined that the suggested configuration change is no longer necessary. 

The current design includes an additional modal triggered by the publication button, which addresses various use cases beyond what the suggested configuration would have covered. As a result, integrating the config change is not currently a priority for ESS-DIVE's UI and user journey flow.

Thank you for your patience and for following up on the PR. Let me know if you have any further questions.

2024-06-04 21:29 UTC, robyngit commented
Thanks @helbashandy ! I figured you had taken a different path, but just didn't want to assume :)