Add CSS to support scrolling in layers toolbar in the Cesium map view
NCEAS/metacatui pull request #2249
Opened 2024-01-20 00:56 UTC by ianguerin

- Set a fixed height for body element to force map view to appear on page.
- Add some padding to allow for scrollbar in layers toolbar.
- Fix issue with cutting off last layer in toolbar on narrow laptop screen due to a hardcoded value for the header height.

GitHub issue: https://github.com/NCEAS/metacatui/issues/2242

2024-01-20 21:49 UTC, mbjones commented
Thanks @ianguerin this is great. Could you provide a screenshot in the PR so folks that don't have a dev-instance of MetacatUI set up can see what the feature will look like?

@robyngit could you review please and maybe this can be included in the release along with the hierarchical data view? Thanks.

2024-01-22 18:03 UTC, ianguerin commented
Here are some before an after screenshots:
Before the layers list was scrollable:
![before being scrollable](https://github.com/NCEAS/metacatui/assets/4664309/790b5290-6149-4968-91f2-b765811fb90e)

After, with the layers list scrollable
![after_scrollable](https://github.com/NCEAS/metacatui/assets/4664309/b9603ebd-93c7-4af5-a1af-965f62f023b9)

Before, when scrolled to the bottom:
![before, scrolled to the bottom](https://github.com/NCEAS/metacatui/assets/4664309/035d2eb1-fa4f-42cd-8e27-7d6535ae305a)

After, when scrolled to the bottom
![after, scrolled to the bottom](https://github.com/NCEAS/metacatui/assets/4664309/c292a15a-26fa-47a4-9619-0083b69b1fae)

2024-01-22 22:22 UTC, robyngit requested changes
Great work, @ianguerin! Thank you for being so proactive on this and congrats on your first MetacatUI PR :tada:! Your changes look perfect for the PDG portal in the arctic theme. I appreciate that you added only the most minimal CSS rules to make this work; it helps keep our already very large CSS file from getting even larger!

Because MetacatUI is used by other projects, it's important for us to check that changes align well across various themes and contexts before merging them into the main codebase. I've outlined some of these considerations below.

### In non-arctic themes

When testing in non-arctic themes, like knb, there seems to be a slight issue: the cesium map expands to accommodate this list, instead of having the list scroll as intended.

To switch to another theme, change `theme: "arctic"` to `theme: "knb"` in the `config.js` file.

### In non-portal contexts

Repositories may also use the cesium map, instead of Google maps, in the main data search catalog. In this context, there's a bit of a display problem. The `overflow: hidden` CSS rule added to the `.map-view__toolbar-container` class is causing the right side of the layer list to be clipped off.

To see this, pull in the `drp` theme from the [metacatui-themes](https://github.com/NCEAS/metacatui-themes/) repo, and configure the `theme` option to `drp`. The search catalog with layer list expanded looks like this:

<img width="1436" alt="Screenshot 2024-01-22 at 16 20 24" src="https://github.com/NCEAS/metacatui/assets/26600641/4536115a-0607-4f9c-a4fd-2f84c77e59d7">


---

We can collaborate on fixing this issue given that other themes and contexts may be outside the scope of your PDG work. In any case, thank you again for this and I look forward to more of your contributions!

2024-01-23 01:26 UTC, ianguerin commented
Thanks for the detailed review, Robyn. I've updated the PR with changes to address the issues you found with the toolbar. It looks like the issue with the `drp` theme was probably broken without any scroll capability (you couldn't actually access the layers in the list below the visible content), so this change should help.

2024-01-25 23:48 UTC, robyngit approved these changes
Nice work @ianguerin!!

2024-01-25 23:49 UTC, merged