Bugfix #2265 portals body height
NCEAS/metacatui pull request #2271
Opened 2024-02-16 21:13 UTC by iannesbitt

From [my comment](https://github.com/NCEAS/metacatui/issues/2265#issuecomment-1949332448) on the issue:

> My solution to this is a little different than the [above method](https://github.com/NCEAS/metacatui/issues/2265#issuecomment-1936748651), instead of using the `.PortalView` element, I set `height: 100%` on `document.style.body` in `PortalVisualizationsView`, and remove the property in `PortalSectionView`. I did this because it echoes the way [the `--footer-height` is set and unset](https://github.com/NCEAS/metacatui/blob/758ff8e3710637d9fdf406a9c2383e56ff5be877/src/js/views/FooterView.js#L30-L42). If it would be cleaner for me to do this another way (such as setting this on `.PortalView`), I'm happy to switch to a different method.

2024-02-20 17:42 UTC, robyngit requested changes
Hey @iannesbitt! Good fix, thanks for picking up this task and working on it so fast (and also finding it in the first place)! One issue I found is that the `height` property that gets set on cesium viz portal pages doesn't get removed if you navigate away from a portal. You can see this if you test locally:
1. Configure the theme to arctic and go to http://localhost:3000/portals/permafrost
2. See that `height: 100%` is set on `body`
3. Click on "Hosted by the Arctic Data Center" in the upper left hand corner
4. See that `height: 100%` is still set on `body`
5. Refresh the page and see that `height: 100%` is no longer on the body

Although this isn't causing issues for this particular page, it could conflict with layout styles on other pages, themes, or in the future. It's best to ensure that we always remove this property when we navigate away from the cesium portal page. Look into how `onClose` is used throughout metacatui, triggered by `AppView.showView`. This is one way to go about it, but definitely not the only way.

2024-02-20 22:00 UTC, iannesbitt commented
That makes total sense, good catch. I originally tried to put it in `PortalVisualizationsView.onClose()` but that function didn't seem to be called when I clicked on another portal section link, and I couldn't figure out why. I didn't think anything of it but I guess that's probably a larger issue to address as well...

2024-02-28 16:34 UTC, robyngit commented
@iannesbitt some background for you: `onClose` is a MetacatUI pattern, not a backbone thing (like I originally assumed when I started working on MetacatUI). Together, the router and AppView orchestrate removing and rendering the main views that make our single page application appear to navigate between different pages. `AppView` calls `onClose` on these "main" views before removing them. The idea is that `onClose` on these main views should then check for `onClose` methods on any sub-views and call those as well. Unfortunately, I think these `parent.onClose() --> child.onClose()` links are missing between views. We once were trying to establish a pattern of saving any `subviews` as a property of the parent view to help facilitate this, but this practice isn't followed consistently in the codebase.

2024-02-28 19:21 UTC, iannesbitt commented
@robyngit That makes sense given that PortalView has a working `onClose` function, but the PortalVisualizationsView one is never called. How are those links created?

2024-02-28 22:52 UTC, robyngit commented
> How are those links created?

@iannesbitt it's a matter of the parent views calling onClose on their subviews when they are closed. Here's an example of how that might look:

```js
ParentView = Backbone.View.extend({
  // ... other parent view methods ...

  createSubView: function () {
    const subView = new SubView();
    // When the parent view creates a subview, it should save a reference to it
    // so that it can call methods on it later.
    this.set("subView", subView);
    // or:
    // this.set('subViews', this.get('subViews').concat(subView));
  },

  onClose: function () {
    // When the parent view is closed, it should close the subview as well.
    const subView = this.get("subView");
    if (typeof subView?.onClose === "function") {
      subView.onClose();
    }
  },
});
```

So it involves a bit of manual work to make sure that the parent view is aware of its subviews and can call `onClose` on them when it is closed itself. There are likely less repetitive and less error-prone ways to implement this behaviour throughout MetacatUI, but this is the convention historically used here and maybe the quickest way to implement it without refactoring the entire codebase.

2024-02-29 17:17 UTC, iannesbitt commented
I get an error when trying `this.set(...)` in `PortalView.addVizSection()` and `PortalView.addSection()` that says the set function does not exist. So instead, I tried going with what's there. It looks like what happens is that the `sectionView` subview is appended to `this.subviews` using `push()`. I tried using `pop()` to get the last element in that array to grab the sectionView and run its `onClose` function, but I get `Uncaught TypeError: undefined has no properties`.

For comparison, when I add `document.body.style.removeProperty("height");` directly to `PortalView.onClose()`, everything works as expected.

This feels like an issue stemming from my lack of js experience, so my apologies if I'm missing something obvious...

2024-02-29 17:40 UTC, robyngit commented
No worries @iannesbitt, the issue you're experiencing is a common source of confusion and errors in JS! The value of the keyword `this` in JS can change depending on context, very unlike `self` in Python. Here is a good [short article](https://dev.to/ibtesum/this-in-javascript-and-self-in-python-any-difference-38fm) describing distinction between the two.

So I think you're getting the error saying that `set` does not exist because `this` isn't what you think it is. You may expect it to be the View that contains the method that is being called, but it may be the object that's calling the method or something else.  Check what `this` is in your code where you're calling `this.set` (with either a `console.log(this)` or a breakpoint in your browser's dev tools) and that might help you figure out what's going wrong.

If it helps, [`Function.prototype.call()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call) can be used to set the value of `this` to a specific object within a function.

`document.body.style.removeProperty("height")` works because `document` is a global object and available everywhere, including in PortalView.

2024-03-04 16:29 UTC, robyngit commented
Works and looks great, @iannesbitt! Thank for finding and fixing this!!

2024-03-04 16:29 UTC, robyngit approved these changes

2024-03-04 16:29 UTC, merged