Feature 1796 places autocomplete
NCEAS/metacatui pull request #2314
Opened 2024-03-19 21:49 UTC by ianguerin

Includes all changes from individual PRs 1,2,3 and 5 (contents of 4 included in earlier PR) that were individually reviewed.

The goal of this PR is to be tested using a more manual review, by running in various themes.

2024-03-21 19:53 UTC, robyngit requested changes
This is going to be fantastic @ianguerin, thanks for keeping it all so modular. I encountered some issues:
1. When there's no maps key configured in a repository, the ToolbarView breaks and the help tab view doesn't get rendered. The console shows the message: `Error rendering ToolbarView section TypeError: gmaps is null`
2. With a map key configured, I actually wasn't able to find any places. I only see the message: "No search results found."

2024-03-21 21:24 UTC, ianguerin commented
> This is going to be fantastic @ianguerin, thanks for keeping it all so modular. I encountered some issues:
> 
> 1. When there's no maps key configured in a repository, the ToolbarView breaks and the help tab view doesn't get rendered. The console shows the message: `Error rendering ToolbarView section TypeError: gmaps is null`
> 2. With a map key configured, I actually wasn't able to find any places. I only see the message: "No search results found."

I've hidden the viewfinder panel if there is not Google Maps API key now. 
I'm curious to reproduce #2 in your list, as it works with my personal API key, so I wonder if there's an API not enabled on the key

2024-03-21 23:02 UTC, robyngit commented
Tested with a properly configured API key, it works so well!! 🎉🎉🎉

2024-03-25 17:11 UTC, robyngit commented on src/js/models/geocoder/GoogleMapsAutocompleter.js
> +      async autocomplete(input) {
```suggestion
      async autocomplete(input) {
        if (!input) return [];
```

2024-03-25 20:40 UTC, robyngit approved these changes

2024-03-25 20:41 UTC, merged