Added configs for layers in the Map Config
NCEAS/metacatui pull request #2482
Opened 2024-07-16 22:53 UTC by alonakos

`clickFeatureAction`

`showOpacitySlider`

2024-07-17 14:00 UTC, robyngit requested changes
Congrats on your first PR!!! 🎉 Thanks so much for working on this! Everything looks great, just need to add some documentation and resolve linting/formatting issues. Details about fixing the linting and formatting errors can be found [here](https://github.com/NCEAS/metacatui/blob/main/CONTRIBUTING.md#-code-style).

2024-07-17 21:13 UTC, alonakos commented on src/js/models/maps/assets/MapAsset.js
> +          showOpacitySlider: true,
Thank you! I just added jsdoc comment in MapAssest. Do you think this looks good?

2024-07-17 21:17 UTC, alonakos commented on src/js/views/maps/LayerDetailsView.js
> +            const detailSection = new LayerDetailView({
I implemented the changes on line 228, line 231 following the reviewdog suggestions.

2024-07-18 14:48 UTC, robyngit commented on src/js/models/maps/assets/MapAsset.js
> +          showOpacitySlider: true,
Looks great! 👍🏻

2024-07-18 14:49 UTC, robyngit commented on src/config/config.js
Oops! I think you commit config/config.js by accident (very easy to do)!

2024-07-18 17:03 UTC, alonakos commented on src/config/config.js
Oops, thank you for pointing it out! Fixed

2024-07-18 17:59 UTC, robyngit approved these changes
🎉 Excellent!!!

2024-07-18 17:59 UTC, merged